version: 0.2

phases:
  build:
    commands:
      - dotnet publish
      - cd ./JuniorTennis.Mvc/bin/Debug/netcoreapp3.1/publish
      - zip -r ../../../../../site.zip *
artifacts:
  files:
    - 'site.zip'
    - 'aws-windows-deployment-manifest.json'
